services:
  rdgen:
    # use bryangerlach/rdgen:latest for the latest build
    #build: .
    image: bryangerlach/rdgen:latest
    restart: unless-stopped
    environment:
      SECRET_KEY: "dYS5H9@Hi{ipJx21gg7lcNtzc~yO*M1Am8fBzb%Z"
      GHUSER: "EduardStn"
      GHBEARER: "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"
      GENURL: "rdgen.tatbox.ru"
      ZIP_PASSWORD: "evFLq}~pQFD9MF95WXMR"
      GHBRANCH: "master"
      PROTOCOL: "https"
      REPONAME: "rdgen"
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
